# Generated by Django 3.0.7 on 2020-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_electronics1_essentials1'),
    ]

    operations = [
        migrations.CreateModel(
            name='furniture1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('rent_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='housing1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('rent_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vehicles1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('rent_price', models.CharField(max_length=50)),
            ],
        ),
    ]
